#!/bin/bash
while true; do
	BATT=$( acpi -b | sed 's/.*[charging|unknown], \([0-9]*\)%.*/\1/gi' )
	STATUS=$( acpi -b | sed 's/.*: \([a-zA-Z]*\),.*/\1/gi' )
	if ([ $BATT -le 10 ] && [ $STATUS == 'Discharging' ]); then
		sudo beep  
	fi
	sleep 5s
done 
