#!/bin/bash
setxkbmap -option 'caps:ctrl_modifier'
xcape -e 'Caps_Lock=Escape'
setxkbmap -option 'caps:ctrl_modifier'
xcape -e 'Caps_Lock=Escape;Control_L=Escape;Control_R=Escape'
setxkbmap -option ctrl:ralt_rctrl
# xmodmap -e "keycode 49 = asciitilde grave"

