#!/bin/bash
local out file key
IFS=$'\n' out=($(fd . ~/Documents/textbooks -e pdf | fzf --query="$1" --exit-0 --expect=ctrl-o,ctrl-e))
# IFS=$'\n' out=($(fd . ~/Documents/textbooks -e pdf | dmenu))
key=$(head -1 <<< "$out")
file=$(head -2 <<< "$out" | tail -1)
if [ -n "$file" ]; then
    [ "$key" = ctrl-o ] && open "$file" || ${READER} "$file" &
fi
