#!/bin/bash
tmux new-session -s main -n "sys" -d
# tmux split-window -v -t main
# tmux split-window -h -t main:1.0
# tmux split-window -h -t main:1.1
tmux send-keys -t main:1 'htop' C-m
# tmux send-keys -t main:1.1 'w3m mail.google.com/mail/u/0/?ui=html' C-m
# tmux send-keys -t main:1.3 'mocp' C-m

tmux new-window -n shell -t main
# tmux send-keys -t main:2 'w3m google.com' C-m

tmux new-window -n kernel -t main
# tmux send-keys -t main:3 'canto' C-m

# tmux new-window -n System -t main
# tmux split-window -h -t main:4
# tmux send-keys -t main:4.0 'top' C-m
# tmux split-window -v -t main:4.1
# tmux send-keys -t main:4.1 'while [ true ]; do clear; sensors; sleep 1; done' C-m
# tmux resize-pane -U -t main:4.2 25

tmux select-window -t main:1
tmux attach -t main
